apiVersion: v1
kind: Service
metadata:
  name: 2048-game
  namespace: game-lab
  labels:
    app: 2048-game
spec:
  type: ClusterIP
  selector:
    app: 2048-game
  ports:
    - name: http
      port: 5000
      targetPort: http
      protocol: TCP
